### ISSUE TITLE
Reading from URL

### ISSUE THREAD

**Issue by SymbolixAU** [ATFutures/geoplumber#53]
In [this line](https://github.com/ATFutures/geoplumber/blob/master/R/geojson.R#L31) you're reading the GeoJSON, converting to sf, then converting back to GeoJSON. 

In summary:
```r
url <- "http://opendata.canterburymaps.govt.nz/datasets/fb00b553120b4f2fac49aa76bc8d82aa_26.geojson"
geojson <- geojsonsf::geojson_sf(url)
geojson <- geojsonsf::sf_geojson(geojson)
```

Would it be more performant to directly read the GeoJSON and leave it as-is, rather than round-tripping to `sf` and back?

```r
geo <- readLines(url)
```

**Comment by layik** [comment]
Thanks @SymbolixAU why did I miss this? It is because we have something more urgent here. Appreciate the input. 

To answer your question:
The rason is that geoplumber is trying to serve the data from internal api endpoints, we discussed this, as you rightly ask, we could probably just read it and dump it to the body of the response object [here](https://github.com/ATFutures/geoplumber/blob/master/R/geojson.R#L37). I will test and update this issue.

It seems `gp_geojson` has no issue reading both from a local path or a remote URL.

Thanks guys!

**Comment by layik** [comment]
```
geo <- readLines(url)
geo <- paste(geo, collapse = "")
```
Seems to work, the reason for this `collapsing` cropped up before, it is to do with underlying packages of `plumber`. But as I do more tests might push and close this. 

One more time, thanks a lot.

**Comment by SymbolixAU** [comment]
yes, that's exactly what I do [here](https://github.com/SymbolixAU/geojsonsf/blob/master/R/geojson_sf.R#L191) too - `paste0(readLines(url), collapse = "")`

**Comment by layik** [comment]
So far all good. Closing and appreciate all your input @SymbolixAU. geojsonsf has made things quite different for me.
